class Keith
  def self.hi
    [
      'Keith has never not been bald',
      'Keith pretends to know German',
      'Keith does all his work in dreamweaver',
      "Keith's favorite color is transparent",
      "Keith owns ten pairs of jeggings",
      "Keith finds Kierkegaard's presupposition on existentialliasm to be rather pedantic",
      "Keith dreams in colors. Specifically in #ggg.",
      "Keith can refactor the entire source code of Citizen using just CSS.",
      "Keith can adapt to any culture thanks to his responsive grid",
      "Keith holds the copyright for the word Keith. In every market domain. Worldwide. Forever.",
      "The real first name of Chuck Norris is Keith, but he changed it for respect to the real Keith.",
      "Keith's favorite design software is Corel Draw 6.",
      "Keith occupies the 345th position in the line of succession to the British throne.",
      "CMYK stands for Cyan, Magenta, Yellow, Keith",
      "Keith can design an artistic masterpiece on a calculator",
      "Keith once challenged Andy Warhol to a design-off. The loser had to start painting cans of soup",
      "Keith can win a game of Connect Four in only three moves",
      "Keith knows the other name for Thesaurus",
      "Keith pays for his fonts",
      "Keith owns a precision scale that can measure font weight",
      "Keith is so low-res he can't even save for web",
      "Keith added Tooth Brush to his Photoshop",
      "Keith can Edit > Undo real life events.",
      "Keith had a small part in Star Wars",
      "Keith shot the serif (but he didn't shoot the deputy)",
      "Underneath Keith's beard is a Wacom tablet.",
      "Keith once sneezed into a tissue and handed it to a struggling artist for inspiration - that artist was Jackson Pollock.",
      "Keith invented this joke: What happened when #ff0000 had a baby with #ffff00? #ff6600",
      "The reason Banksy decided to have a secret identity? Keith told him to do it.",
      "Keith is currently in his blue period",
      "Keith can grant you three wishes if you ask politely",
      "GOOD was initially known as The GOOD. Keith suggested to drop The.",
      "Keith can round pixels even though he can't count.",
      "Keith only orders from a dropdown menu.",
      "Keith's New Year's resolution is 300dpi.",
      "Keith can spot serifs a mile away.",
      "Keith's handwriting is Comic Sans.",
      "Keith is terrified of dying and going to Helvetica.",
      "Keith thinks 'kern' is on the cob.",
      "Keith is a trademark, but everyone can use it as long as they credit Keith.",
      "Keith's grandparents were half French and half Italic.",
      "Lorem Ipsum is Keith's native tongue.",
      "Keith got his first haircut in utero.",
      "Keith's cat makes him sleep on the floor."
    ].sample
  end
end
